spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true