spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  main:
    allow-bean-definition-overriding: true
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - month_2.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local