spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      data-locations: data.sql
      mode: always
      schema-locations: schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true