CREATE TABLE IF NOT EXISTS GENRES
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    GENRENAME VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS AUTHORS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL
);
CREATE TABLE  IF NOT EXISTS BOOKS
(
    BOOK_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BOOKNAME VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHORS(ID) NOT NULL ,
    GENRE_ID BIGINT REFERENCES GENRES(ID) NOT NULL
);